# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/o_o/Projects/pusearch/app (2)/ui/default.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame_Default(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        # Frame.resize(1000, 6000)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.webView = QtWebKitWidgets.QWebView(Frame)
        self.webView.setUrl(QtCore.QUrl("https://www.google.com"))  # about:blank
        self.webView.setObjectName("webView")
        self.gridLayout.addWidget(self.webView, 0, 0, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))

from PyQt5 import QtWebKitWidgets
